# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "ホーム"
  url = "#cover"
  weight = 10

[[main]]
  name = "協会について"
  url = "/about"
  weight = 20

[[main]]
  name = "寄付のお願い"
  url = "/donation"
  weight = 30

[[main]]
  name = "お知らせ"
  url = "#news"
  weight = 40

[[main]]
  name = "プレスリリース"
  url = "#press-release"
  weight = 50

[[main]]
  name = "お問い合わせ"
  url = "#contact"
  weight = 60

[[main]]
  name = "ストア"
  url = "/store"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
